### ISSUE TITLE
从tdengine迁移到tdengine报错

### ISSUE THREAD

**Issue by cyr100** [taosdata/DataX#42]
java.lang.UnsatisfiedLinkError: Native Library C:\Windows\System32\taos.dll already loaded in another classloader
 at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1900) ~[na:1.8.0_261]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850) ~[na:1.8.0_261]
        at java.lang.Runtime.loadLibrary0(Runtime.java:871) ~[na:1.8.0_261]
        at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_261]
        at com.taosdata.jdbc.TSDBJNIConnector.<clinit>(TSDBJNIConnector.java:28) ~[taos-jdbcdriver-2.0.42.jar:na]
        at com.taosdata.jdbc.TSDBDriver.connect(TSDBDriver.java:162) ~[taos-jdbcdriver-2.0.42.jar:na]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_261]
        at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[na:1.8.0_261]
        at com.alibaba.datax.plugin.writer.tdengine20writer.DefaultDataHandler.handle(DefaultDataHandler.java:77) ~[tdengine20writer-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.plugin.writer.tdengine20writer.TDengineWriter$Task.startWrite(TDengineWriter.java:109) ~[tdengine20writer-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:56) ~[datax-core-0.0.1-SNAPSHOT.jar:na]

**Comment by twtmiss** [comment]
读和写不能同时用JNI连接，一个用JNI，一个用RESTFUL就可以了，等着看什么时候能解决吧，我现在用着是真的感觉不如用大厂成熟的数据库，起码没有这么多问题。。。
